name: CD
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  push-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Pushed Notification Text
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            START BUILD
            *${{ github.repository }}*
            *${{ github.event.commits[0].message }}*
  
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: registry.dev.gbms.site/gbms-site:latest

  build-notify:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Builded Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            BUILD-PUSH COMPLETE
            *${{ github.repository }}*
            *${{ github.event.commits[0].message }}*
  deploy:
    runs-on: ubuntu-latest
    needs: build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://${{ secrets.DOCKER_HOST }}
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: stack deploy --compose-file docker-compose.yml gbms-site
          

  deploy-notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deployed Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            DEPLOY COMPLETE
            *${{ github.repository }}*
            *${{ github.event.commits[0].message }}*
